### ISSUE TITLE
Related questions about "event"

### ISSUE THREAD

**Issue by SHNU-cpy** [spjuhel/BoARIO#123]
In the “event” module, you have defined two types of events, one for recover and one for rebuild, I would like to know the difference between the two.
If it is a recover event, what are the specific measures to restore the destroyed capital and production capacity?
If it is a rebuild, what are the specific measures taken to restore the destroyed capital and production capacity?
Also how are the reconstruction requirements entered into the model?

**Comment by spjuhel** [comment]
Hi,
For these types of questions, refer to the online documentation. Raising issues should be done only when encountering a problem with the package or to suggest improvements.

In your case, both questions are answered here: https://spjuhel.github.io/BoARIO/tutorials/boario-events.html
