### ISSUE TITLE
Minimal example shows shortage before shock

### ISSUE THREAD

**Issue by spjuhel** [spjuhel/BoARIO#7]
Find out why and fix

**Comment by aleeciu** [comment]
In my case, with "ARIOBase" I get quite a funny output. Here is a notmalized losses plot:
![output](https://user-images.githubusercontent.com/29018864/196984984-f5e681f3-3ead-47d0-b40e-1b3b3be46b83.png)

But with ARIOpsi, it looks just fine:
![output_psi](https://user-images.githubusercontent.com/29018864/196985185-e98bf996-53ad-47ee-84df-8d696bc10d21.png)
